development:
  secret_key_base: 1d7...fc1
  mail_username: welcome.myMealz@gmail.com
  mail_password: supersecretpassword

  GLOBAL_GATEWAY_ID: QJ6813-95
  GLOBAL_GATEWAY_PASS: 6XvIBm6kkAAmKvmVPizE19LgvZ2VQvVv

  stripe_publish_key: 'pk_test_YckyRwbXyLyOLyjpCSFJOA1q'
  stripe_secret_key: 'sk_test_7HZcxLdo3hWGb1ymhA9QZB2G'
