source 'https://rubygems.org'

gem 'rails', '~> 5.1.4'
gem 'sqlite3'

# Using Devise Gems
#https://rubygems.org/gems/devise
#Flexible authentication solution for Rails with Warden
gem 'devise'


# Jquery for rails
gem 'jquery-rails'

# for Twitter UIComponents
gem 'bootstrap-sass', '>= 3.3.7'

# Use SCSS for stylesheets
gem 'sass-rails', '>= 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use unicorn as the app server
#gem 'unicorn'
# Use Puma as the local app server
#gem 'puma', '>= 3.7'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '>= 4.2'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '>= 5'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '>= 2.5'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Gems used only for assets and not required
# in production environments by default.
#group :assets do
 # gem 'sass-rails', '>= 5.0'
 # gem 'coffee-rails', '>= 4.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
 # gem 'therubyracer', :platforms => :ruby

#end
